const { Pool } = require('pg');
require('dotenv').config();

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false
});

// Create tables if they don't exist
const initializeDatabase = async () => {
  try {
    console.log('🔧 Initializing database schema...');
    
    // Check if uuid-ossp extension is available
    try {
      await pool.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";');
      console.log('✅ UUID extension enabled');
    } catch (err) {
      console.log('⚠️  UUID extension not available, IDs will be generated by application');
    }

    // Create rooms table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS rooms (
        id UUID PRIMARY KEY,
        name VARCHAR(255) NOT NULL UNIQUE,
        description TEXT,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
      );
    `);
    
    // Create messages table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS messages (
        id UUID PRIMARY KEY,
        room_id UUID REFERENCES rooms(id) ON DELETE CASCADE,
        username VARCHAR(100) NOT NULL,
        text_content TEXT,
        image_url VARCHAR(500),
        created_at TIMESTAMP DEFAULT NOW()
      );
    `);
    
    // Create indexes
    try {
      await pool.query('CREATE INDEX IF NOT EXISTS idx_messages_room_id ON messages(room_id);');
      await pool.query('CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at DESC);');
      await pool.query('CREATE INDEX IF NOT EXISTS idx_rooms_updated_at ON rooms(updated_at DESC);');
      console.log('✅ Database indexes created');
    } catch (err) {
      console.log('⚠️  Some indexes may already exist');
    }
    
    console.log('✅ Database schema initialized successfully');
    
    // Create trigger function if supported
    try {
      await pool.query(`
        CREATE OR REPLACE FUNCTION update_room_timestamp()
        RETURNS TRIGGER AS $
        BEGIN
          UPDATE rooms SET updated_at = NOW() WHERE id = NEW.room_id;
          RETURN NEW;
        END;
        $ LANGUAGE plpgsql;
      `);
      
      // Create trigger
      try {
        await pool.query(`
          CREATE TRIGGER update_room_on_message
          AFTER INSERT ON messages
          FOR EACH ROW
          EXECUTE FUNCTION update_room_timestamp();
        `);
        console.log('✅ Database triggers created');
      } catch (err) {
        console.log('⚠️  Trigger may already exist');
      }
      
    } catch (err) {
      console.log('⚠️  Database triggers not supported or already exist');
    }
    
  } catch (err) {
    console.error('❌ Database initialization error:', err);
  }
};

// Initialize database on connection
pool.on('connect', () => {
  console.log('✅ Connected to PostgreSQL database');
  initializeDatabase();
});

pool.on('error', (err) => {
  console.error('❌ Database connection error:', err);
});

module.exports = pool;